name: Issue
description: Report a general issue not covered by other templates.
title: "<[Title of Issue]>"
labels: ["type:issue"]
body:

  - type: textarea
    id: issue_description
    attributes:
      label: Description
      description: Describe the issue, why it matters, and any context that helps explain it.
      placeholder: Tell us about your issue!
    validations:
      required: true

  - type: textarea
    id: visuals
    attributes:
      label: Visual Aids
      description: Add any screenshots, gifs, diagrams, or other visual references.
      placeholder: Add any screenshots, gifs, diagrams, or other visual references.
      value: |
        <details>
          <summary> Expand ⬇️ </summary>
          <!-- add GIFs/Screenshots/Videos/Diagrams here -->
          <!-- Leave a blank line below -->



        </details>

  - type: input
    id: related_issues
    attributes:
      label: Related Issues
      description: Mention any related issue numbers, like "#123".

  - type: markdown
    attributes:
      value: Sample code, additional context, etc.
