name: ✒️ Issue ✒️
description: Report a general issue not covered by other templates.
title: "Issue: [Title of Issue]"
labels: ["type:issue"]
body:

  - type: textarea
    id: issue_description
    attributes:
      label: Description
      description: Describe the issue, why it matters, and any context that helps explain it.
      placeholder: |
        Tell us about your issue!

        List any tasks you need to accomlish this issue.
        Tasks:
          ✅ Task 1
          ✅ Task 2

    validations:
      required: true

  - type: textarea
    id: visuals
    attributes:
      label: Visual Aids
      description: (Optional, but recommended) Add any screenshots, gifs, diagrams, or other visual references.
      placeholder: Add any screenshots, gifs, diagrams, or other visual references.
      value: |
        <details>
          <summary> Expand ⬇️ </summary>
          <!-- add GIFs/Screenshots/Videos/Diagrams here -->
          <!-- Leave a blank line below -->



        </details>

  - type: textarea
    id: issue_checklist
    attributes:
      label: Issue Checklist
      description: Please confirm the following before creating this issue.
      value: |
        <details>
        <summary>Issue Checklist (click to expand)</summary>

        - [ ] I have a clear description of the issue
        - [ ] I have assigned myself to this issue
        - [ ] I have assigned a label to this issue
        - [ ] I have assigned a project to this issue
        - [ ] I have linked my branch to this issue

        </details>

  # If you want the checklist to be required, add the following:
  # It will prevent users from submitting the issue without checking the boxes
  # but it will be visible in the issue unless deleted after creation 

  # - type: checkboxes
  #   id: checklist
  #   attributes:
  #     label: Checklist
  #     description: Confirm the following before submitting
  #     options:
  #       - label: I have a clear description of the issue
  #         required: true
  #       - label: I have assigned myself to this issue
  #         required: true
  #       - label: I have assigned a label to this issue
  #         required: true
  #       - label: I have assigned a project to this issue
  #         required: true
    


