name: Issue
description: Report a general issue not covered by other templates.
labels: ["type:issue"]
body:
  - type: input
    id: issue_title
    attributes:
      label: Issue Title
      description: A clear and descriptive title for this issue.
    validations:
      required: true

  - type: textarea
    id: issue_description
    attributes:
      label: Description
      description: Describe the issue, why it matters, and any context that helps explain it.
    validations:
      required: true

  - type: textarea
    id: visuals
    attributes:
      label: Visual Aids
      description: Add any screenshots, gifs, diagrams, or other visual references.
      render: shell

  - type: input
    id: related_issues
    attributes:
      label: Related Issues
      description: Mention any related issue numbers, like "#123".

  - type: markdown
    attributes:
      value: Sample code, additional context, etc.

assignees:
  - "username"